### ISSUE TITLE
Winetricks doen't open even though it's installed.

### ISSUE THREAD

**Issue by masakk1** [flathub/net.brinkervii.grapejuice#22]
Using Pop os, winetricks comes with it. I tried updating it but nothing. I tried searching for some sort of setting I had to enable but I can't see anything.
Every time I click `Wine apps > Winetricks` this error shows up:
```lua
Traceback (most recent call last):
  File "/app/lib/python3.10/pip_deps/grapejuice/background.py", line 82, in run
    self.work()
  File "/app/lib/python3.10/pip_deps/grapejuice/tasks.py", line 179, in work
    self._prefix.core_control.run_linux_command(self._app)
  File "/app/lib/python3.10/pip_deps/grapejuice_common/wine/wineprefix_core_control.py", line 482, in run_linux_command
    return do_run_exe(
  File "/app/lib/python3.10/pip_deps/grapejuice_common/logs/log_util.py", line 13, in wrapper
    result = func(*args, **kwargs)
  File "/app/lib/python3.10/pip_deps/grapejuice_common/wine/wineprefix_core_control.py", line 158, in do_run_exe
    subprocess.call(
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'winetricks'
```

Any help is appreciated. Thanks.

**Comment by guihkx** [comment]
Yeah, launching a system-installed `winetricks` from a Flatpak app will not work.

I guess one option is to also package `winetricks` within this app...

@Thelolguy1 thoughts?

**Comment by lunarlattice0** [comment]
Sure, I can package winetricks with the flatpak. I will admit this is the first time I've seen anyone use winetricks with grapejuice.

**Comment by lunarlattice0** [comment]
Do you happen to be the same person asking this question on the discord?

**Comment by lunarlattice0** [comment]
![image](https://user-images.githubusercontent.com/18731514/209626210-1e3fb26c-3c06-4daa-902f-46f38048f195.png)

**Comment by guihkx** [comment]
Pardon me as I don't know who the person on the screenshot is, but I disagree.

Having Winetricks packaged is actually helpful to install older versions of DXVK, for example.

By default, Grapejuice chooses the latest version of DXVK, but that's not necessarily correct or wanted behavior. On older GPUs (that can still play Roblox just fine), DXVK 2.0 won't work due to a hard dependency on Vulkan 2.0.

Grapejuice even plans to implement this: https://trello.com/c/h7QDvR1H/74-dxvk-version-selector

In my opinion, since Winetricks is just a single bash script file of ~900 KiB, it wouldn't hurt to package it to make it much easier for people to install whatever components they like.

If you change your mind about this, but you're not interested in actually adding it yourself, just let me know and I can send a PR.

**Comment by masakk1** [comment]
@guihkx I agree it can be useful. However, if you ever REALLY need to use the flatpak version then go for the other versions available.
IMO making this clearer would be great though. Such as adding a disclaimer that said "this version of grapejuice doesn't have winetricks" every time you try to open it. Among any other tools that are missing.
Or, if possible, add an option to install winetricks along the previous mentioned disclaimer. This would be dope.
Then again, like he said, it's not that big a deal if it's that small.

I leave the decision to the devs :smile:

**Comment by masakk1** [comment]
> Do you happen to be the same person asking this question on the discord?

Yeah I was.
Sorry for the extreme late reply
