### ISSUE TITLE
Experiment with vanilla Wine?

### ISSUE THREAD

**Issue by guihkx** [flathub/net.brinkervii.grapejuice#9]
I'm almost sure the mouse cursor bug was fixed by the Roblox devs at some point, because I ran Roblox with vanilla Wine 6.11 and couldn't reproduce the bug anymore.

I think that having this Flatpak package to rely on [org.winehq.Wine](https://github.com/flathub/org.winehq.Wine) is probably better than using a custom patched Wine version (that we don't know how it was even built).

Thoughts?

**Comment by lunarlattice0** [comment]
The mouse cursor bug is in fact fixed (except in XWayland, but there really isn't a patch for that). However, the wine bundled with the flatpak comes with the low-fragmentation heap patch which helps reduce the performance losses over play time greatly. The wine build itself is relatively reliable, since the source is Grapejuice's maintainer (BrinkerVII), and sandboxing already removes access to files and severely limits other system access. I am willing to accept PRs to this flatpak to add an independent build, though.

**Comment by guihkx** [comment]
>However, the wine bundled with the flatpak comes with the low-fragmentation heap patch which helps reduce the performance losses over play time greatly.

Oh, nice. I actually didn't know that. Anywhere I can find the build recipe for this custom Wine build by BrinkerVIII or is it private?

If a custom Wine build contains patches other than the mouse fix one, I suppose it makes a lot of sense to keep using it.

**Comment by lunarlattice0** [comment]
The ZST wine archive in the yaml should include the build recipe, if my
memory serves me right. Please feel free to join the grapejuice Discord to
ask Brinker directly if the configuration file isn't there.

**Comment by guihkx** [comment]
Unfortunately, the .zst just contains the pre-compiled Wine binary. I went [to Gitlab](https://gitlab.com/brinkervii/wine-builds/) expecting the build recipe to be there, but it isn't. I guess I'll have to ask him. Thanks!

**Comment by lunarlattice0** [comment]
This is a bit late, but the patches should be in the zst archive under
opt/wine-tkg/wine-tkg-userpatches and opt/wine-tkg/customization.cfg.

**Comment by guihkx** [comment]
Oh, I missed it. I'll definitely check it out, thanks again!

**Comment by sewnie** [comment]
> he wine bundled with the flatpak comes with the low-fragmentation heap patch which helps reduce the performance losses over play time greatly.

i cannot confirm this, but i can confirm that it has higher fps but over time there *is* performance loss, is that what LFH does?
